apiVersion: v1
kind: Secret
metadata:
  name: syncope
  labels:
    app: sitewhere
    chart: sitewhere
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: c3luY29wZQ==
